team_homepage:
    path:     /
    defaults: { _controller: TeamBundle:Default:index }

createteam:
    path:     /createteam
    defaults: { _controller: TeamBundle:team:createteam }

readteam:
    path:     /readteam
    defaults: { _controller: TeamBundle:team:readteam }

updateteam:
    path:     /updateteam
    defaults: { _controller: TeamBundle:team:updateteam }

deleteteam:
    path:     /deleteteam
    defaults: { _controller: TeamBundle:team:deleteteam }
